In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/ar_properties.csv")

In [2]:
caba_sales = df[
    (df["operation_type"] == "Venta") &
    (df["property_type"] == "Departamento") &
    (df["l2"] == "Capital Federal") &
    (df["currency"] == "USD")
].copy()

In [3]:
caba_sales.shape

(121442, 25)

In [4]:
caba_sales["surface_total"].isna().sum()

np.int64(24688)

In [5]:
(caba_sales["surface_total"] <= 0).sum()

np.int64(19)

In [6]:
caba_sales["surface_total"].describe()

count     96754.000000
mean         93.669357
std         835.945152
min           0.000000
25%          42.000000
50%          60.000000
75%          90.000000
max      108960.000000
Name: surface_total, dtype: float64

In [7]:
(caba_sales["surface_total"] > 500).sum()

np.int64(350)

In [9]:
caba_sales[caba_sales["surface_total"] > 500][
    ["surface_total", "price", "rooms", "bedrooms", "l3", "l4"]
].sort_values("surface_total", ascending=False)

        surface_total      price  rooms  bedrooms            l3   l4
48021        108960.0   290000.0    3.0       2.0  Villa Crespo  NaN
831523       104890.0   255000.0    4.0       3.0  Barrio Norte  NaN
789876       104890.0   240000.0    4.0       3.0  Barrio Norte  NaN
730364       104890.0   265000.0    4.0       3.0  Barrio Norte  NaN
789875       104890.0   240000.0    4.0       3.0  Barrio Norte  NaN
...               ...        ...    ...       ...           ...  ...
34624           510.0  1620000.0    8.0       5.0      Belgrano  NaN
188865          510.0  1620000.0    8.0       5.0      Belgrano  NaN
147759          508.0  2100000.0    5.0       4.0      Recoleta  NaN
84003           502.0   850000.0    6.0       NaN      Recoleta  NaN
925654          502.0   850000.0    8.0       NaN      Recoleta  NaN

[350 rows x 6 columns]

In [10]:
caba_sales[caba_sales["surface_total"] > 500][
    ["surface_total", "price", "rooms", "bedrooms", "l3", "l4"]
].sort_values("surface_total", ascending=False).head(20)

        surface_total      price  rooms  bedrooms                   l3   l4
48021        108960.0   290000.0    3.0       2.0         Villa Crespo  NaN
831523       104890.0   255000.0    4.0       3.0         Barrio Norte  NaN
789876       104890.0   240000.0    4.0       3.0         Barrio Norte  NaN
730364       104890.0   265000.0    4.0       3.0         Barrio Norte  NaN
789875       104890.0   240000.0    4.0       3.0         Barrio Norte  NaN
62754         47360.0   116000.0    3.0       2.0              Almagro  NaN
654584        44180.0   166100.0    2.0       NaN            Caballito  NaN
653708        32180.0   111385.0    1.0       NaN            Caballito  NaN
677729        21920.0    43000.0    1.0       1.0             Congreso  NaN
919927        21920.0    50000.0    1.0       1.0             Congreso  NaN
501896        17444.0   435000.0    5.0       3.0             Belgrano  NaN
664121        17180.0   500000.0    4.0       3.0             Belgrano  NaN
89065         14834.0  1250000.0    4.0       3.0              Palermo  NaN
587887        14081.0   340000.0    3.0       2.0            San Telmo  NaN
10211         12521.0   270000.0    3.0       2.0             Belgrano  NaN
283069        11626.0   285000.0    4.0       3.0             Belgrano  NaN
364055        11250.0   229000.0    4.0       3.0    Parque Centenario  NaN
587350        10838.0   251665.0    2.0       1.0            San Telmo  NaN
232957        10370.0   255000.0    3.0       2.0  Villa General Mitre  NaN
421483        10259.0   320000.0    4.0       3.0             Recoleta  NaN

In [11]:
(caba_sales["surface_total"] > 1000).sum()

np.int64(145)

In [12]:
(
    (caba_sales["surface_total"] > 500) &
    (caba_sales["surface_total"] <= 1000)
).sum()

np.int64(205)

In [13]:
(caba_sales["surface_total"] < 10).sum()

np.int64(19)

In [14]:
caba_sales[caba_sales["surface_total"] < 10]["surface_total"].value_counts()

surface_total
0.0    19
Name: count, dtype: int64

In [15]:
caba_sales[
    (caba_sales["surface_total"] > 500) &
    (caba_sales["surface_total"] <= 1000)
][["surface_total", "price", "rooms", "bedrooms", "l3", "l4"]].sort_values(
    "surface_total", ascending=False
)

        surface_total      price  rooms  bedrooms            l3   l4
204399         1000.0   240000.0    3.0       NaN  Barrio Norte  NaN
265236          999.0   127000.0    2.0       NaN      Congreso  NaN
220069          980.0   295000.0    1.0       1.0      Recoleta  NaN
637754          978.0  5700000.0   10.0       4.0      Recoleta  NaN
651773          943.0  1100000.0   16.0      16.0     San Telmo  NaN
...               ...        ...    ...       ...           ...  ...
133821          510.0  1620000.0    8.0       5.0      Belgrano  NaN
34624           510.0  1620000.0    8.0       5.0      Belgrano  NaN
147759          508.0  2100000.0    5.0       4.0      Recoleta  NaN
84003           502.0   850000.0    6.0       NaN      Recoleta  NaN
925654          502.0   850000.0    8.0       NaN      Recoleta  NaN

[205 rows x 6 columns]

In [20]:
q1 = caba_sales["surface_total"].quantile(0.25)
q3 = caba_sales["surface_total"].quantile(0.75)
iqr = q3 - q1

print(q1)
print(q3)
print(iqr)

42.0
90.0
48.0

In [21]:
lower_limit = q1 - 1.5 * iqr
upper_limit = q3 + 1.5 * iqr

print(lower_limit)
print(upper_limit)

-30.0
162.0

In [22]:
(caba_sales["surface_total"] > upper_limit).sum()

np.int64(7470)

In [23]:
caba_sales["price"].isna().sum()

np.int64(0)

In [24]:
(caba_sales["price"] <= 0).sum()

np.int64(0)

In [25]:
caba_sales["price"].describe()

count    1.214420e+05
mean     2.363164e+05
std      4.100945e+05
min      5.000000e+03
25%      1.079480e+05
50%      1.550000e+05
75%      2.480000e+05
max      4.553535e+07
Name: price, dtype: float64

In [26]:
caba_sales[caba_sales["price"] < 20_000][
    ["price", "surface_total", "rooms", "bedrooms", "l3"]
]

          price  surface_total  rooms  bedrooms                l3
9164    12000.0           13.0    1.0       1.0           Liniers
9165    12000.0           13.0    1.0       1.0           Liniers
9166    12000.0           13.0    1.0       1.0           Liniers
9167    12000.0           13.0    1.0       1.0           Liniers
9168    12000.0           13.0    1.0       1.0           Liniers
25350   14000.0           44.0    1.0       1.0        Colegiales
49059   14500.0          405.0    5.0       NaN           Palermo
155679  18000.0           12.0    NaN       NaN  Villa del Parque
223844   6000.0          195.0    5.0       3.0     Puerto Madero
233907  18000.0           11.0    NaN       NaN           Almagro
297193   7500.0           31.0    1.0       1.0  Parque Chacabuco
361733   6000.0          275.0    3.0       2.0     Puerto Madero
364649  10500.0           50.0    3.0       2.0           Liniers
467662   6000.0          340.0    3.0       2.0          Recoleta
472553  10000.0         2000.0    2.0       NaN     Villa Urquiza
472556  10000.0         2000.0    2.0       NaN     Villa Urquiza
484521  12500.0           18.0    1.0       1.0         Caballito
484522  12500.0           18.0    1.0       1.0         Caballito
495424  11111.0          200.0    4.0       NaN          Recoleta
503350  19000.0           42.0    1.0       NaN         Caballito
516913  15000.0            NaN    4.0       2.0               NaN
524940  11000.0           55.0    2.0       1.0         San Telmo
591145  11111.0           50.0    3.0       NaN             Nuñez
613322   5000.0          455.0    7.0       NaN          Recoleta
634592   6000.0          340.0    5.0       4.0           Palermo
643753  11803.0           34.0    1.0       NaN           Palermo
648629  11111.0           90.0    4.0       NaN          Congreso
667749  10000.0            NaN    2.0       1.0           Palermo
668049  14000.0           35.0    2.0       1.0      Villa Devoto
683759  10800.0           60.0    3.0       2.0           Almagro
737518  11500.0           63.0    3.0       2.0            Flores
747983  10000.0            NaN    3.0       NaN     Puerto Madero
769337  17000.0           12.0    NaN       NaN         Caballito
788076  15000.0           42.0    2.0       1.0           Almagro
796124  10000.0            NaN    1.0       NaN            Flores
796276  12000.0            NaN    2.0       NaN          Floresta
851271   8000.0            NaN    4.0       NaN     Puerto Madero
929924  18900.0           82.0    3.0       2.0       Parque Chas
976663   9500.0           35.0    2.0       1.0         Balvanera

In [27]:
q1_price = caba_sales["price"].quantile(0.25)
q3_price = caba_sales["price"].quantile(0.75)

iqr_price = q3_price - q1_price

print(q1_price)
print(q3_price)
print(iqr_price)

107948.0
248000.0
140052.0

In [28]:
lower_limit_price = q1_price - 1.5 * iqr_price
upper_limit_price = q3_price + 1.5 * iqr_price

print(lower_limit_price)
print(upper_limit_price)

-102130.0
458078.0

In [29]:
(caba_sales["price"] > upper_limit_price).sum()

np.int64(10462)

In [30]:
caba_sales[caba_sales["price"] > 5_000_000][
    ["price", "surface_total", "rooms", "bedrooms", "l3"]
]

             price  surface_total  rooms  bedrooms             l3
4472    11111111.0            NaN    NaN       NaN          Nuñez
59539    5800000.0          677.0    8.0       5.0       Recoleta
100856   7897000.0           41.0    1.0       NaN      Caballito
105016   9876543.0            NaN    NaN       NaN        Palermo
107680  32434232.0           43.0    1.0       1.0        Palermo
118478   6000000.0          600.0    6.0       3.0       Recoleta
124821   5000345.0           60.0    3.0       NaN    San Nicolás
125076   8500000.0          690.0    4.0       NaN       Belgrano
149878  12345678.0            NaN    3.0       NaN       Recoleta
169044   7897000.0           41.0    1.0       NaN      Caballito
169834   5200000.0            NaN    4.0       3.0            NaN
171367   5112000.0           41.0    1.0       NaN      Caballito
182651   5500000.0            NaN    6.0       NaN       Belgrano
215064   7897000.0           41.0    1.0       NaN      Caballito
238796  34567678.0            NaN    3.0       NaN     Tribunales
271015   5250000.0          404.0    4.0       NaN        Palermo
271144   8000000.0          410.0    5.0       NaN        Palermo
271190   6750000.0          540.0    5.0       NaN  Puerto Madero
273273   9477000.0           41.0    1.0       NaN      Caballito
287736  12345678.0            NaN    3.0       NaN       Saavedra
355126   7897000.0           41.0    1.0       NaN      Caballito
357330   6500000.0          771.0    5.0       3.0  Puerto Madero
360768  23456789.0            NaN    2.0       NaN  Villa Ortuzar
375850  12345678.0            NaN    NaN       NaN   Villa Devoto
390245  11111111.0            NaN    3.0       2.0            NaN
413257   8748000.0           41.0    1.0       NaN      Caballito
425658  12345678.0            NaN    3.0       NaN  Villa Ortuzar
431541  23456789.0            NaN    1.0       NaN       Recoleta
507348  45535353.0            NaN    3.0       NaN        Palermo
510806   6000000.0          600.0    6.0       3.0       Recoleta
553158   9477000.0           41.0    1.0       NaN      Caballito
573092  12345678.0            NaN    3.0       NaN  Villa Ortuzar
632595  23456789.0            NaN    NaN       NaN       Belgrano
637754   5700000.0          978.0   10.0       4.0       Recoleta
657439   9477000.0           41.0    1.0       NaN      Caballito
713609   6500000.0          265.0    4.0       3.0  Puerto Madero
784602  34567999.0            NaN    3.0       NaN        Palermo
786724  10082032.0           31.0    1.0       NaN    San Nicolás
796095  12121212.0            NaN    2.0       NaN            NaN
805557   5112000.0           41.0    1.0       NaN      Caballito
809143   5800000.0          600.0    4.0       3.0       Recoleta
830883   9477000.0           41.0    1.0       NaN      Caballito
851711   5500000.0            NaN    4.0       NaN          Nuñez
873749   6500000.0          771.0    5.0       3.0  Puerto Madero
901749  34567678.0            NaN    3.0       NaN     Tribunales
962075   9477000.0           41.0    1.0       NaN      Caballito
972889  12564363.0            NaN    4.0       3.0      Caballito

In [31]:
valid_surface = caba_sales[
    caba_sales["surface_total"] > 0
].copy()

print(valid_surface.shape)

(96735, 25)

In [32]:
valid_surface["price_per_m2"] = (
    valid_surface["price"] / valid_surface["surface_total"]
)

valid_surface["price_per_m2"].describe()

count     96735.000000
mean       2918.580622
std        3639.060377
min           1.961679
25%        2250.000000
50%        2700.000000
75%        3275.862069
max      754284.465116
Name: price_per_m2, dtype: float64

In [33]:
valid_surface[
    valid_surface["price_per_m2"] > 20_000
][
    ["price", "surface_total", "price_per_m2", "rooms", "l3"]
].sort_values("price_per_m2", ascending=False)

             price  surface_total   price_per_m2  rooms                 l3
107680  32434232.0           43.0  754284.465116    1.0            Palermo
786724  10082032.0           31.0  325226.838710    1.0        San Nicolás
962075   9477000.0           41.0  231146.341463    1.0          Caballito
830883   9477000.0           41.0  231146.341463    1.0          Caballito
657439   9477000.0           41.0  231146.341463    1.0          Caballito
273273   9477000.0           41.0  231146.341463    1.0          Caballito
553158   9477000.0           41.0  231146.341463    1.0          Caballito
413257   8748000.0           41.0  213365.853659    1.0          Caballito
100856   7897000.0           41.0  192609.756098    1.0          Caballito
169044   7897000.0           41.0  192609.756098    1.0          Caballito
215064   7897000.0           41.0  192609.756098    1.0          Caballito
355126   7897000.0           41.0  192609.756098    1.0          Caballito
805557   5112000.0           41.0  124682.926829    1.0          Caballito
171367   5112000.0           41.0  124682.926829    1.0          Caballito
124821   5000345.0           60.0   83339.083333    3.0        San Nicolás
8600     3150000.0           54.0   58333.333333    2.0      Puerto Madero
388567    476000.0           11.0   43272.727273    4.0       Barrio Norte
517009   3249900.0           82.0   39632.926829    3.0           Recoleta
608144   3900000.0          101.0   38613.861386    NaN      Villa Urquiza
85527     630000.0           17.0   37058.823529    NaN           Recoleta
176555   1350000.0           39.0   34615.384615    NaN           Belgrano
886320   1111111.0           36.0   30864.194444    1.0            Almagro
463148   3300000.0          108.0   30555.555556    5.0      Puerto Madero
713609   6500000.0          265.0   24528.301887    4.0      Puerto Madero
657983    690000.0           30.0   23000.000000    1.0      Villa Urquiza
274301    275000.0           12.0   22916.666667    4.0       Villa Crespo
363764   1000000.0           45.0   22222.222222    2.0   Parque Patricios
145371   1110000.0           50.0   22200.000000    1.0   Parque Chacabuco
174409   1045000.0           48.0   21770.833333    NaN         Colegiales
370211    239000.0           11.0   21727.272727    3.0  Parque Centenario
54102    1250000.0           61.0   20491.803279    2.0            Palermo
716402   1111111.0           55.0   20202.018182    3.0       Villa Lugano

In [34]:
valid_surface[
    valid_surface["price_per_m2"] > 20_000
][
    ["price", "surface_total", "surface_covered", "price_per_m2", "rooms", "l3"]
].sort_values("price_per_m2", ascending=False)

,price,surface_total,surface_covered,price_per_m2,rooms,l3
107680,32434232.0,43.0,43.0,754284.465116,1.0,Palermo
786724,10082032.0,31.0,NaN,325226.838710,1.0,San Nicolás
962075,9477000.0,41.0,37.0,231146.341463,1.0,Caballito
830883,9477000.0,41.0,37.0,231146.341463,1.0,Caballito
657439,9477000.0,41.0,37.0,231146.341463,1.0,Caballito
273273,9477000.0,41.0,37.0,231146.341463,1.0,Caballito
553158,9477000.0,41.0,37.0,231146.341463,1.0,Caballito
413257,8748000.0,41.0,37.0,213365.853659,1.0,Caballito
100856,7897000.0,41.0,37.0,192609.756098,1.0,Caballito
169044,7897000.0,41.0,37.0,192609.756098,1.0,Caballito
215064,7897000.0,41.0,37.0,192609.756098,1.0,Caballito
355126,7897000.0,41.0,37.0,192609.756098,1.0,Caballito
805557,5112000.0,41.0,37.0,124682.926829,1.0,Caballito
171367,5112000.0,41.0,37.0,124682.926829,1.0,Caballito
124821,5000345.0,60.0,56.0,83339.083333,3.0,San Nicolás
8600,3150000.0,54.0,54.0,58333.333333,2.0,Puerto Madero
388567,476000.0,11.0,125.0,43272.727273,4.0,Barrio Norte
517009,3249900.0,82.0,73.0,39632.926829,3.0,Recoleta
608144,3900000.0,101.0,96.0,38613.861386,NaN,Villa Urquiza
85527,630000.0,17.0,165.0,37058.823529,NaN,Recoleta
176555,1350000.0,39.0,39.0,34615.384615,NaN,Belgrano
886320,1111111.0,36.0,33.0,30864.194444,1.0,Almagro
463148,3300000.0,108.0,108.0,30555.555556,5.0,Puerto Madero
713609,6500000.0,265.0,265.0,24528.301887,4.0,Puerto Madero
657983,690000.0,30.0,30.0,23000.000000,1.0,Villa Urquiza
274301,275000.0,12.0,115.0,22916.666667,4.0,Villa Crespo
363764,1000000.0,45.0,40.0,22222.222222,2.0,Parque Patricios
145371,1110000.0,50.0,46.0,22200.000000,1.0,Parque Chacabuco
174409,1045000.0,48.0,44.0,21770.833333,NaN,Colegiales
370211,239000.0,11.0,63.0,21727.272727,3.0,Parque Centenario
54102,1250000.0,61.0,55.0,20491.803279,2.0,Palermo
716402,1111111.0,55.0,45.0,20202.018182,3.0,Villa Lugano

In [35]:
(
    valid_surface["surface_covered"] > valid_surface["surface_total"]
).sum()

np.int64(800)

In [36]:
valid_surface["surface_difference"] = (
    valid_surface["surface_covered"] - valid_surface["surface_total"]
)

In [37]:
valid_surface[
    valid_surface["surface_covered"] > valid_surface["surface_total"]
][
    ["surface_total", "surface_covered", "surface_difference", "price", "rooms", "l3"]
].sort_values("surface_difference", ascending=False)

,surface_total,surface_covered,surface_difference,price,rooms,l3
818379,175.0,15560.0,15385.0,279000.0,4.0,San Nicolás
447101,145.0,13402.0,13257.0,510000.0,4.0,Colegiales
370416,132.0,13235.0,13103.0,605000.0,4.0,Palermo
690345,136.0,12846.0,12710.0,359000.0,4.0,Recoleta
322949,117.0,8760.0,8643.0,230000.0,3.0,Barrio Norte
...,...,...,...,...,...,...
464916,23.0,24.0,1.0,47000.0,1.0,Monserrat
463753,75.0,76.0,1.0,125000.0,3.0,Once
223442,76.0,77.0,1.0,155000.0,3.0,Balvanera
463477,19.0,20.0,1.0,65000.0,1.0,Recoleta
993951,59.0,60.0,1.0,190000.0,3.0,Caballito

In [38]:
valid_surface[
    valid_surface["surface_difference"] > 0
]["surface_difference"].describe()

count      800.00000
mean       212.73125
std       1264.84784
min          1.00000
25%          1.00000
50%          1.00000
75%          6.00000
max      15385.00000
Name: surface_difference, dtype: float64

In [39]:
(valid_surface["surface_difference"] > 50).sum()

np.int64(59)

In [40]:
analysis_df = caba_sales[
    caba_sales["surface_total"].notna() &
    (caba_sales["surface_total"] > 0) &
    (caba_sales["price"] > 0)
].copy()

In [41]:
analysis_df["price_per_m2"] = (
    analysis_df["price"] / analysis_df["surface_total"]
)

In [42]:
print(analysis_df.shape)
analysis_df[
    ["price", "surface_total", "surface_covered", "price_per_m2"]
].describe()

(96735, 26)

              price  surface_total  surface_covered   price_per_m2
count  9.673500e+04   96735.000000     94194.000000   96735.000000
mean   2.419592e+05      93.687755        82.469021    2918.580622
std    3.280022e+05     836.026213       751.623363    3639.060377
min    5.000000e+03      10.000000         0.000000       1.961679
25%    1.100000e+05      42.000000        39.000000    2250.000000
50%    1.590000e+05      60.000000        54.000000    2700.000000
75%    2.500000e+05      90.000000        80.000000    3275.862069
max    3.243423e+07  108960.000000    104890.000000  754284.465116

In [43]:
analysis_df.to_csv(
    "../data/processed/caba_apartments_clean.csv",
    index=False
)

OSError: Cannot save file into a non-existent directory: '../data/processed'

In [44]:
analysis_df.to_csv(
    "../data/processed/caba_apartments_clean.csv",
    index=False
)

In [45]:
caba_sales.to_csv(
    "../data/processed/caba_apartments_base.csv",
    index=False
)